near/near-contract-helper

app.js
Should follow https://github.com/nearprotocol/nearcore/pull/310
=> Switch account to plain strings

README.md, app.js
```
http post http://localhost:3000/account newAccountId=nosuchuseryet.near newAccountPublicKey=22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV
```
For some reason getting error:
```
invalid type: map, expected a string at line 1 column 8
```
=> Wait for account creation using `waitForTransactionResult`

app.js, package-lock.json, package.json
We should also find way to securely store the keypair for a new account.
=> Modify contract helper to conform to the new way of deploying contract

app.js
Original issue: https://github.com/nearprotocol/near-wallet/issues/231
=> Modify recovery link for email/phone

app.js, test/app.test.js
We need to include public key in order ensure that we delete the correct recovery method. https://github.com/nearprotocol/near-wallet/pull/381
=> require public key to delete recovery method

migrations/20200429204207-move-security-code-to-recovery-methods.js, migrations/20200430184429-contrain-recoverymethod-unique-kind-detail.js
Migrations:
- Move securityCode from Account to RecoveryMethod
- Require RecoveryMethod to be unique (e.g. can only be one hi@near.org email)
=> migrations for recovery methods

migrations/20200429204207-move-security-code-to-recovery-methods.js, migrations/20200430184429-contrain-recoverymethod-unique-kind-detail.js, models/account.js, models/recovery-method.js, yarn.lock
[All other related changes to near-contract-helper (132)](https://github.com/near/near-contract-helper/pull/132)
[All other related changes to near-wallet (559)](https://github.com/near/near-wallet/pull/559)
**TODO:**
- Add migration for `recoveryMethod` `confirmed` flag. Old accounts will need to have `confirmed` set to `true` in order to show up on profile
=> add recovery migrations and model changes

middleware/2fa.js
This PR attaches 100 TGas to the confirm transaction in contract helper.
=> attach gas to confirm

middleware/2fa.js
This PR updates email subject lines for both regular transactions, including the receiver_id of the transaction and a warning subject line for transactions where a full access key will be added to the account.
=> Update email subjects

middleware/2fa.js, package.json, yarn.lock
=> Display more details in 2FA message

README.md, app.js, middleware/indexer.js, package.json, yarn.lock
Highlights:
- Deduplicate account IDs when querying indexer DB
- Add error monitoring using Sentry
=> Maintenance Release 2020-11-05

middleware/2fa.js, utils/email.js
=> update fak email to include accountId and publicKey

middleware/indexer.js
Reverts near/near-contract-helper#299
=> Release 2020-12-23 reboot

middleware/indexer.js
Note that this is blocked until we confirm that implicit accounts are covered ok by indexer
=> Don't include deleted accounts/keys when querying from indexer

middleware/indexer.js
Follow up to https://github.com/near/near-contract-helper/pull/407 that I forgot to push
=> Fix /callReceivers query

migrations/20210607051723-add-fundedAccountNeedsDeposit-to-accounts.js
Migration to add flag to track fundedAccountNeedsDeposit column to Accounts table
=> 426 - Add fundedAccountNeedsDeposit to Account table

package.json, yarn.lock
+ Dependency bumps
+ Migration to add `fundedAccountNeedsDeposit` to the Account table
=> Release 2021-06-10 (1)

middleware/indexer.js
- Use pool.query() helper instead of rolling our own.  
- Add pool-level logging (of request going to the explorer indexer) for debugging.
=> Use pg-pool query helper instead of rolling our own

middleware/indexer.js
Existing search was finding `metapool.near` which is a non-standard API resulting in incorrect total balances displayed in wallet
=> Use more restrictive search for staking deposits

middleware/indexer.js
Removed some code duplication and introduced a single source of truth for magic strings
=> Normalize pool matching behaviour for staking deposits and validators endpoints

migrations/20210909003022-add-IdentityVerificationMethods.js, migrations/20210909003422-add-IdentityVerificationMethods-constraints.js
Part of coin-op v1.5, adding verification methods table
=> Add IdentityVerificationMethods table w/ basic constraints

middleware/indexer.js, migrations/20210909003022-add-IdentityVerificationMethods.js, migrations/20210909003422-add-IdentityVerificationMethods-constraints.js
=> Release 2021-09-08

migrations/20210909003022-add-IdentityVerificationMethods.js, migrations/20210909003422-add-IdentityVerificationMethods-constraints.js
=> Release 2021-09-09

RecaptchaValidator/RecaptchaValidator.js, middleware/fundedAccount.js, middleware/identityVerificationMethod.js, package.json, yarn.lock
Add recaptcha enterprise / v3 recaptcha
=> Recaptcha enterprise

middleware/identityVerificationMethod.js, migrations/20210917010954-addUniqueIdentityKey.js, migrations/20210917011012-add-IdentityVerificationMethods-unique-identityKey-constraint.js
=> Release 2019-09-20 #4

app.js, middleware/identityVerificationMethod.js
=> Release 2021-09-23

app.js, middleware/identityVerificationMethod.js
=> Release 2021-09-24

README.md
Fixes https://github.com/near/near-contract-helper/issues/516
=> Replace HTTPie with CURL

README.md, middleware/indexer.js
- Added support for detecting NFTs that were minted using the new NEP171 events structure
=> 2021-12-01 Release 

middleware/fundedAccount.js
- Avoids corner case where we get error about 'not enough storage...' instead of a 'NotEnoughBalance' error from NAJ
=> Ensure we return NotEnoughBalance errors when coin-op is low on funds

middleware/fundedAccount.js
=> 2021-12-23 Release

middleware/indexer.js
update pool query patterns to match accounts matching both the old `*.poolv1.near` and newly added `*.pool.near`
=> feat: update pool query patterns to match new staking pools

middleware/indexer.js
Adds factory from [staking-farm](https://github.com/referencedev/staking-farm/blob/master/HowTo.md) repo to indexer staking pool queries on testnet.
=> fix: add testnet stake&farm factory pool pattern

middleware/indexer.js
Add validators using wallet's factory `factory.colorpalette.testnet` as well as aurora's `factory01.littlefarm.testnet` to pool pattern
=> chore: add new factory to pool pattern

features/flags.json
**Do not merge before the contract helper service in render.com is offline**
=> 2022-03-28 Release 2

Jenkinsfile
This PR modifies the Jenkins CI behavior to work with our non-trunk-based approach using `stable`/`master` and adds branch restrictions for PRs.
=> fix(ci): Jenkins CI updates

Jenkinsfile
This PR updates the Jenkinsfile to install dependencies prior to testing.
=> fix(ci): install before testing

.env.sample, app.js, middleware/nearpay.js
=> feat(integration): NearPay integration

middleware/indexer.js
Add indexer queries for any Fungible Token ownership change events per Fungible Token Event [standard](https://nomicon.io/Standards/Tokens/FungibleToken/Event)
=> feat: add indexer query for fungible token events

Dockerfile, ecs/contract-helper.container-definition.json, ecs/indexer.container-definition.json
This PR defines ECS container definitions for both contract-helper and indexer services. This is a step towards packaging task definitions along with application code within our CI pipeline.
=> WAL-341 Add ECS container definitions

package.json, src/db/utils.js
Pulling #620 into a local branch to get around conflicts
=> feat: Allow for running the container using custom environment variables

app.js, ci/Jenkinsfile
=> 2022-06-25 Release

app.js, indexer.js, package.json, yarn.lock
This PR replaces the existing logger with a `bunyan` implementation which adds a structured JSON format as well as more verbose logging.
=> feat: Replace `koa-logger` with `koa-bunyan-logger`

.github/workflows/pull-request.yml
This PR adds a Github action which targets pull requests and will run lint/test.
=> ci: Add workflow to run code checks on PRs

src/middleware/indexer.js
Add filters for deleted accts / keys
=> Fix filters on findAccountsByPublicKey endpoint to QueryAPI
