.editorconfig
This tells editors to use 4 spaces for indentation, which matches existing code in this repository
Many editors come with built-in support for this file. If yours doesn't, you can download a plugin at https://editorconfig.org/#download
=> refactor: add editorconfig

.env.sample, README.md, app.js, package.json, test/app.test.js
This mostly boils down to README improvements, but does introduce one **breaking change**:
* Rather than expecting `CREATOR_KEY` and `RECOVERY_KEY` to have a `private_key` attribute, they are now expected to have a `secret_key`.  This makes it simpler to get started, since `~/.near/validator_key.json` can be copied directly, with no key renames.
Most other noise here comes from the fact that all `.env` settings are now required – this simplifies the code. Many of these were already required but poorly documented; this documents them.
Also interesting: note that the `start` command has changed to use `sed` instead of just `cat`. This is necessary to strip end-of-line comments.  These end-of-line comments provide a much nicer onboarding experience and code-organization/maintenance scheme …
=> refactor: improve getting-started experience

app.js
This `console.error` is only relevant if we're not yet dealing with this error type, so moving it to the bottom of this function is more appropriate.
This also means we no longer have a loud console error when running the tests. This console output made me think the tests weren't working at first!
=> refactor: don't show console.error when testing

README.md, app.js, package.json, test/app.test.js, yarn.lock
* Upgrade `nearlib` to `near-api-js`
* Add `dotenv` to make it easier to test (test file wasn't reading env from `.env` without it)
* Add instructions for testing to README
=> refactor: nearlib→near-api-js; improve testing

app.js, test/app.test.js
Accounts created before we started saving publicKeys will not be able to send them along to these endpoints, so we need to allow them to be null
=> fix: allow null publicKey

app.js, test/app.test.js
Access Keys added for specific contracts should not be able to expose all of a user's recovery methods
=> fix: ensure request comes from a FullAccess key

app.js, test/app.test.js
[Wallet changes (559)](https://github.com/near/near-wallet/pull/559)
[Migrations and model changes for this code (135)](https://github.com/near/near-contract-helper/pull/135)
Covered in this PR:
- Initialize an ‘unconfirmed’ recovery method (email/phone) without a publicKey and adding a securityCode
- Validate securityCode
- Add publicKey to Recoverymethod (‘confirmed’) before sending recovery message
- Create new endpoint to ‘re-send’ recovery link
=> add recovery method verification

middleware/2fa.js
This PR replaces data provided by client to contract helper that is emailed to 2FA method, with data from the chain pertaining to the request_id the user is seeking to confirm.
Additional multisig hash:
There is a new version of multisig that cleans up some contract storage issues and allows for unconfirmed (older than 15m) requests to be removed.
Linted. All tests passing locally.
e2e testing with wallet locally using a Render instance of this PR works fine and sends the desired email/sms.
Thanks to @abacabadabacaba for spotting this vulnerability.
=> fix for sending email with on-chain request data

app.js, middleware/2fa.js, package.json, utils/email.js
PR updates utils/email.js to include the new template and creates 2 helper functions for recovery link emails and 2FA emails.
Messaging is according to: https://github.com/near/near-wallet/issues/751
- actions are broken out and simplified from their JSON
- args from function call are parsed from base64 and remain JSON (we won't have schema for random function calls)
Tested:
- Recovery
- Single actions
- Multiple actions (rotate keys)
Kendall has approved screenshots. Please try against your local wallet:
https://near-contract-helper-2fa.onrender.com
=> Update Email Template and 2FA Messaging

app.js, middleware/2fa.js, middleware/near.js, test/app.test.js, utils/email.js
This PR includes several improvements to the account creation emails.
The text versions are also updated.
This has been tested with @Patrick1904 latest wallet fix PR for account creation: https://github.com/near/near-wallet/pull/841
As per @corwinharrell new design and copy:
=> Fix Account Creation Emails (now with code + recovery)

README.md
The readme was instructing to run a local NEAR network by cloning `nearcore`, but this is no longer the recommended approach
=> docs: update obsolete localnet instructions

app.js, utils/email.js
We no longer user this method from the wallet.
Part of ongoing maintenance re: account creation updates.
=> deprecate sendRecoveryMessage

middleware/2fa.js, test/2fa.test.js
**PR Fixes:**
- Deposit on functionCall 2FA message: https://github.com/near/near-contract-helper/issues/234
- Fix gas exceeded error for app sign confirm of function calls that require more than default gas (attach 100 Tgas vs. default 30)
- Update verify emails for 2FA to include accountId
=> Fix email 2fa

middleware/indexer.js
Reverts near/near-contract-helper#298
Currently https://helper.mainnet.near.org/publicKey/xxx/ is unresponsive.
It seems like `WALLET_INDEXER_DB_CONNECTION` variable wasn't set in the production.
=> Revert "Release 2020-12-23"

.eslintrc.yml, .mocharc.js, README.md, app.js, constants.js, middleware/2fa.js, package.json, test/.env.test, test/.eslintrc.yml, test/2fa.test.js, test/TestAccountHelper.js, test/app.test.js, test/attachEchoMessageListeners.js, test/chai.js, test/createTestServerInstance.js, test/expectRequestHelpers.js, utils/email.js, utils/sms.js, yarn.lock
**1. Replaces Jest with Mocha/Chai/Sinon**
- Added @types for the new packages for nicer dev experience
- Added custom eslintrc for `test` directory so that eslint doesn't believe that mocha globals exist in our main codebase files
- Updated README.md referencing Jest accordingly
- Modified package.json `test` task entry to use `yarn` to run lint instead of `npm`
**2. Cleans up integration test files for `2fa` and `app`**
- **Consolidated a bunch of shared setup and boilerplate** into `test/TestAccountHelper` class that is responsible for the interactions between the test server, keypair, keystore, etc.
- Replaced manual mutation of `process.env` with a dedicated `test.env` dotEnv file; the existing code used `dotEnv` to load _some_ things, but then manually mutated `env` with others, …
=> Test cleanup / Jest -> Mocha/Chai/Sinon

middleware/2fa.js
Ensures `request` is available in `getAddingFullAccessKeyMessageContent()` -- `destination` was being passed instead, incorrectly.
This bug was just introduced during introduction of acceptance tests for message content from branch `test-message-content`.
There were no tests covering this logic in the 2fa test suite, so I am adding a new test case for this.  This PR will fix the immediate problem, however.
=> Fix "adding FAK" 2FA logic

middleware/indexer.js
Right now when user has withdrawn tokens from Ref Finance they don't show up if they weren't already in the list.
This can be confusing, so we can change to detect `storage_deposit` calls done by user as they basically correspond to "account creation" for given token. 
Here's example call performed by Ref Finance UI:
https://explorer.near.org/transactions/9d5VmLphGMCR5ijPCzXdZcaQnqT4BTjesb7JzGXryqsB
=> Detect likely tokens by querying for `storage_deposit` calls

RecaptchaValidator/RecaptchaValidator.js, middleware/accountCreation.js, test/RecaptchaValidator.js
1. When we encounter a known error, we now return the body payload as JSON, with shape { success, result?, message?, code? }.  
- When `success` is `true`, `result` will contain the transaction result from the account creation, but `message` and `code` will not exist
- When `success` is `false`, `message` and `code` will contain details about what caused the failure
- If an unknown error is encountered while trying to create the account, it will be thrown via `ctx.throw` which returns just the stringified error in the body.
2. Updated reCaptcha POST behavior to use multi-part form posting, as the Google API endpoint doesn't accept JSON 🤦  :)
=> 1659 - Funded Accounts - Update error response shape and use form-data posts for API calls

app.js, middleware/accountCreation.js, package.json, yarn.lock
Endpoint checks the available balance in the source account used for creating funded accounts, and returns whether or not that account has enough balance to provide a funded account to the user.
This will allow us to hide the entire reCAPTCHA flow entirely in cases where the funded account has no more remaining balance, rather than the user still being forced to solve the reCAPTCHA, only to be directed to the implicit account creation screen after they have solved it.
=> 1659 - Add checkFundedAccountAvailable endpoint

app.js
Enables proxy functionality for koa server, which will fix the issue with `koa-ratelimit` not getting accurate IPs for bucketing rate limited requests.
=> Enable proxy ip address detection in for koa

app.js, middleware/fundedAccount.js, middleware/near.js
Bugfix for https://github.com/near/near-wallet/issues/1752 - which is only live on staging & testnet currently.
1. Resolves a bug where any new funded accounts that were created using email or SMS recovery methods did not have their `fundedAccountNeedsDeposit` set to `true`, because those recovery methods create an account record in SQL before any post to `/fundedAccount` is done, but the existing logic in `/fundedAccount` assumed it would be the creator of the account.
2. Added an initial check to make the `/fundedAccount` route throw an error if someone hits it with an accountID that already exists, by leveraging existing middleware named `checkAccountDoesNotExist`
- Modified `checkAccountDoesNotExist` to be a factory function, `createCheckAccountDoesNotExistMiddleware()` so that we …
=> Funded account with recovery code (lock fix)

middleware/indexer.js
Testnet appears to be having some problems with SQL concurrency against explorer; trying increasing the pool size to observe behavioural changes as a troubleshooting step
=> Increase pool size to allow more concurrent clients (troubleshooting)

.github/dependabot.yml, middleware/indexer.js
- Disables dependabot automatic PR creation for minor dependency version bumps, while leaving it enabled for security specific PRs
- Remove debugging changes made to the pg pool object
=> 2021 07 maintenance

app.js, middleware/indexer.js
Facilitates looking up staking pool/validators using a real-time indexer query rather than a static github user content json file (which is by now quite out of date).
Set 1 hour cache window on this list, since the list of staking pools changes rarely, to save Indexer some work.
=> near-wallet/2011 - Add `stakingPools` endpoint and associated indexer query

migrations/20210909003422-add-IdentityVerificationMethods-constraints.js
Turns out `unique` type constraints must be uniquely named even if applied to different tables, which does not appear to by the case for `check` type constraints.
=> Ensure constraints have unique names

app.js, middleware/fundedAccount.js, middleware/identityVerificationMethod.js
- Comment around DB constraint causing a `UniqueConstraintError` to be thrown
- Pulled validation of verification method params into a single method rather than duplicating it in two endpoints
- Fixed incorrect error code being returned if a VerificationMethod existed has already claimed in `createIdentityVerifiedFundedAccount()`
- Made `code string` for `verificationCodeRequired` error consistent with other errors
- Centralized error codes and statusCodes that are specific to Identity Verification
=> Clean-up, code de-duplication and comments

migrations/20210917010954-addUniqueIdentityKey.js, migrations/20210917011012-add-IdentityVerificationMethods-unique-identityKey-constraint.js
Add uniqueIdentityKey column to support for deduping of aliased addresses, with unique constraint to avoid any duplicates ever existing
=> Add unique email column + constraint for IdentityVerificationMethods

.eslintrc.js, app.js, middleware/fundedAccount.js, middleware/identityVerificationMethod.js, models/identity-verification-method.js
Adds `uniqueIdentityKey` to the identityVerificationMethod table so that aliased e-mails are considered identical for the purposes of our duplicate checking.
=> Enable unique email

middleware/indexer.js
The new table `assets__non_fungible_token_events` contains logged nft events.
Currently this query will find all distinct contracts that emitted an event involving the accountId.  In the future this could be improved, e.g. tracking transfers and burns to exclude no longer valid contract associations.
=> feat: add query to indexer to collect mint events for accountId

middleware/fundedAccount.js
- Avoids corner case where we get error about 'not enough storage...' instead of a 'NotEnoughBalance' error from NAJ
- :facepalm: type coercion :tm:
=> Ensure we return NotEnoughBalance errors when coin-op is low on funds

.env.sample, yarn.lock
- Updated follow-redirects dep due to security vuln
- #542 Update pool lookup patterns to find `*.pool.near` validators (v2 'project' pools support)
- Updated sample .env (Thanks @DDeAlmeida ! :))
=> 2022-01-14 Release

features/flags.json
This PR toggles the `USE_DB_SERVICES` feature flag on in the mainnet environments, enabling the usage of the new DB service methods rather than inline SQL queries via `sequelize`.
=> feat: enable USE_DB_SERVICES flag on mainnet

package.json, yarn.lock
This PR seeks to update the transient dependencies with vulnerabilities, which currently break FOSSA tests
=> WAL-95 fix: add resolutions for transient dependencies

Dockerfile, Jenkinsfile, app.js, package.json
This PR adds a Jenkinsfile for deploying to the new AWS environments. The container defined in the new `Dockerfile` is built and pushed to ECR before updating the staging and live services running on the target environment's ECS cluster.
=> WAL-94 feat: Jenkins AWS deployment

middleware/2fa.js, test/2fa.test.js
When a user signs up for 2FA with an email address/SMS number that is already used as a recovery method, the current behavior is to not send the initial verification code as the communication channel has already been verified by virtue of belonging to an existing recovery method owned by the account holder. However this behavior can be unexpected and give the impression to users that their 2FA contract is not securely configured, undermining any convenience that this behavior may have sought to provide.
By ceasing to query for a corresponding recovery method, we ensure that the enabling 2FA always sends an initial code for the user to verify.
Closes #558
=> feat(2fa): don't bypass initial 2FA verification for existing recovery methods

app.js, db/dynamo.js, db/methods/recovery_method/update.js, services/recovery_method.js
This PR is a follow-up to #550 to address some minor bugs and clean up some unnecessarily confusing logic:
- DB methods deleting documents are no longer expected to always return the deleted document (this may be a bug in the DynamoDB library we're using but doesn't affect any code currently).
- `detail` has been removed from the set of key parameters when updating recovery methods as it is no longer part of the composite range key.
- The `listRecoveryMethods` method has been replaced with a new method (`validateSecurityCode`) to verify that the requested recovery method exists with the provided security code. This removes the catch-all filter logic in `listRecoveryMethods`, a method which now is only called when `USE_DYNAMODB` is disabled and can be deleted once the flag is removed 🎉
=> WAL-92 DynamoDB services updates

app.js, db/methods/recovery_method/update.js, middleware/fundedAccount.js, services/identity_verification_method.js, services/recovery_method.js
This PR addresses issues outlined in [WAL-160](https://nearinc.atlassian.net/browse/WAL-160):
- adds an update expression to the recovery method `update` DB method to ensure a value for `createdAt` when document is created via upsert
- use `publicKey` in recovery method validation endpoints to ensure the full range key can be composed (requires [near-wallet PR](https://github.com/near/near-wallet/pull/2529))
- update service calls to always use the DB methods injected in the service constructor, not the DB method imported into module scope
- restore the missing `kind` parameter to `getIdentityVerificationMethod` call when querying Postgres (removed in #550)
=> WAL-160 DynamoDB fixes

db/schemas/recovery_method.js, middleware/fundedAccount.js, services/identity_verification_method.js, services/recovery_method.js, test/.env.test, test/2fa.test.js, test/TestAccountHelper.js, test/app.test.js, test/local_dynamo.js, test/services/account.js, test/services/email_domain_blacklist.js, test/services/identity_verification_method.js, test/services/recovery_method.js
This PR addresses breaking tests when the `USE_DYNAMODB` feature flag is enabled, as well as adding test coverage for new methods and deprecating coverage for methods not called when `USE_DYNAMODB` is enabled.
These changes to are primarily due to minor disparities between how `sequelize` and `dynamodb` handle particular data interactions but also include one-off changes to existing tests for more consistent behavior and to accommodate the in-memory DynamoDB instance, including:
- validation of `null` input values
- casting of date types returned from the DB
- record creation behavior when a matching record already exists
- missing comparison of data points
- providing missing data to endpoints
=> test(db): update tests for DynamoDB integration

features/flags.json
This PR enables the `USE_DYNAMODB` feature flag in `development` and `testnet`* environments. It must be merged during the service downtime to ensure that, once live, all writes go to DynamoDB instead of Postgres.
=> feat(db): enable USE_DYNAMODB in development/testnet environments

middleware/indexer.js
This PR refactors the SQL indexer query responsible for fetching the 10 most recent transactions for a given account. The new query returns exactly the same data but has been rewritten with CTEs to filter the set of rows from `action_receipt_actions` before joining on `receipts`.
Highlights from differences in `EXPLAIN ANALYZE`:
Before: `Limit  (cost=54057.77..54070.61 rows=110 width=385) (actual time=46.483..52.653 rows=97 loops=1)`
After: `Limit  (cost=17650.94..17650.96 rows=10 width=187) (actual time=1.450..1.457 rows=10 loops=1)`
Before: `->  Nested Loop  (cost=381.50..52830.61 rows=5838 width=385) (actual time=0.364..1.818 rows=32 loops=3)`
After: `->  Nested Loop  (cost=0.70..64.70 rows=20 width=187) (actual time=0.862..1.403 rows=13 loops=1)`
Original query results from Postgres …
=> refactor(indexer): recent transactions query tuning

middleware/indexer.js
This PR restores use of the `limit` query string parameter to the endpoint responsible for returning the list of recent transactions. I've added a cap of 100 on the returnable limit to ensure a reasonable amount of data is returned.
I have opted to leave the `offset` parameter out for now, as the responsibility for this endpoint should be fetching the most recent transactions. If pagination ends up being a requirement for non-wallet usage then we should look at designing a separate endpoint that can make this query in such a way that does not incur an unnecessary performance hit.
=> fix(indexer): restore limit parameter with cap

app.js
- Seems that SQL planner has decided this query should take way more effort to fulfill than it should -- temporarily disabling it for stability of the frontend
=> Temporarily disable recent activity endpoint

middleware/indexer.js
This PR restores the recent transactions SQL query to the original implementation. When the endpoint responsible for making this query is re-enabled we will want to resume using the original query as the updated query continues to exhibit abysmal performance.
Note that the only change from the original implementation is the addition of a hard limit on the number of rows returned, which should preclude abuse of the endpoint.
=> fix(indexer): restore original recent transactions query

middleware/2fa.js, services/recovery_method.js, test/2fa.test.js
This PR ensures that reenabling 2FA methods with a different `kind` and/or `detail` correctly overwrites the existing document to ensure that the new method is used. This is possible because the wallet frontend does not delete 2FA recovery method documents when they are disabled in the UI. As a result the old document still exists when 2FA is reenabled and is not updated correctly.
Fixes #612 
Likely fixes https://github.com/near/near-wallet/issues/2638
=> fix(2fa): overwrite disabled 2FA records when changing type

app.js, middleware/near.js, test/app.test.js
This PR bypasses the account ownership check on creation of recovery methods for ledger (`/account/ledgerKeyAdded`) and seed phrases (`/account/seedPhraseAdded`) if the account:
1. Does not exist on-chain
1. Has an implicit account ID
For named accounts which exist on-chain there is no change, if the named account does not exist the middleware will return `403`.
This change is to support creation of zero-balance ledger/seed phrase accounts.
---
- refactor(near): Extract account existence check to own function
- feat(account): Skip ownership check if implicit account doesnt exist
- test(account): Test account ownership skip for ledger/seed phrase
=> feat: Bypass account ownership check on ledger/seed phrase recovery creation for non-existent implicit accounts

.github/CODEOWNERS, ci/Jenkinsfile
This PR moves `Jenkinsfile` back to this repo from `near-wallet-infrastructure`. Additionally, `CODEOWNERS` has been added to protect this file.
=> Restore `Jenkinsfile`

app.js
This PR removes the indexer endpoints from`app.js` as they are now served from `indexer.js`
=> chore(indexer): remove endpoints from app.js

app.js
Adds default behaviour that disables eager reservation of funded accounts using verified identity when creating recovery method during new account creation - we don't use this functionality anymore, and the issue appears to be caused by an issue in the deployment environment (can't load our .json file)
=> fix: disable eager reservation of funded accounts

ecs/contract-helper.container-definition.json
Appears to be a regression from migration to ECS; new accounts are only getting 10N but have been getting 200N historically :)
=> (fix) Configure testnet new accounts to get 200N

indexer.js, src/middleware/indexer.js
This PR adds functionality to query a block timestamp range by adding a `fromBlockTimestamp` query param to the `/likelyTokens` and `/likelyNFTs` endpoint
=> feat: fromBlockTimestamp query param to support caching

src/middleware/indexer.js
According to the node-cache documentation: https://www.npmjs.com/package/node-cache
Current TTL time is set incorrectly (60 seconds instead of wanted 1 hour); This PR fixes this issues
=> Fix: set validators cache time to 1 hour

src/middleware/indexer.js
This PR adds an error listener to `pg.Pool` to avoid the error bubbling up and causing the node process to crash. The error is caught and logged. `Pool` should handle re-connection under the hood.
=> feat: Add error listener to postgres pool

.github/workflows/deployment-pipeline.yml
`pull_request` trigger was left mistakenly left behind while testing the deployment pipeline
=> fix: Dont run deployment pipeline from PRs

.github/workflows/deployment-pipeline.yml
The current behavior is to `cancel-in-progress` workflows when a new one starts. This could potentially leave our infrastructure in a bad state as the job would only be partially finished.
This PR removes the cancel behavior making deployments run serially, allowing them to complete before the next is triggered. This does cause delays if we are merging PRs in quick succession, but as that is rare in the repository it shouldn't cause any problems.
=> ci: prevent subsequent merges cancelling in progress deployments

local_dynamo.js, scripts/create-dynamodb-tables.js
This PR makes it possible to override the hardcoded host/ports for the local/test DynamoDB instance using environment variables. The defaults will continue to reference the original hardcoded values.
=> feat: configurable dynamodb-local instance

src/middleware/indexer.js
This PR removes a reference from the indexer queries to a soon-to-be-deprecated table (`assets__fungible_token_events`). As this table will be removed entirely on March 1st 2023, it must be removed from Contract Helper to prevent queries from breaking.
This table is only referenced from within a subquery used to find fungible tokens. Removing this query will reduce the efficacy/reliability of fungible tokens query, in particular those FTs for which the only record of ownership is a transfer of ownership from another account.
https://github.com/near/near-indexer-for-explorer/discussions/351
=> fix: remove reference to assets__fungible_token_events

src/middleware/indexer.js, test/app.test.js
Trying out a way to recycle connections to see if that improves client behavior.
https://github.com/brianc/node-postgres/tree/master/packages/pg-pool#maxuses-and-read-replica-autoscaling-eg-aws-aurora
=> feat: set maxUses

src/middleware/indexer.js
Closes https://github.com/near/near-contract-helper/issues/684
Related to https://github.com/near/queryapi/issues/325
The response continues the same using QueryAPI
```
curl -XGET http://localhost:3050/publicKey/ed25519:FXFhPD2aYw6YZB9pa9UYJNkJgKGuWDsJvDH13B5NjehL/accounts
```
QueryAPI response:
Explorer DB record:
=> Migrate findAccountsByPublicKey endpoint to QueryAPI
